### ISSUE TITLE
Version 3.0.0 upgrades to Pydantic v2

### ISSUE THREAD

**Issue by andygarfield** [sanders41/camel-converter#351]
I really don't know if this can be fixed, but version 3.0.0 auto-upgrades to Pydantic v2, which has broken a number of things in our CI pipeline.
https://github.com/sanders41/camel-converter/blob/1e38f5b2822706b5aecefb555fc853fcbf9f9cdf/pyproject.toml#L25

This fixes things:
```diff
diff --git a/pyproject.toml b/pyproject.toml
index 005ce2f..1e632f5 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -22,7 +22,7 @@ include = ["camel_converter/py.typed"]
 
 [tool.poetry.dependencies]
 python = "^3.7"
-pydantic = {version = ">=1.8.2", optional = true}
+pydantic = {version = "^1.8.2", optional = true}
 
 [tool.poetry.extras]
 pydantic = ["pydantic"]
```

**Comment by sanders41** [comment]
I can't pin to < 2 because I have users using both Pydantic 1 and Pydantic 2. Can you provide an example of the error you are getting?

**Comment by sanders41** [comment]
Oh, wait...you are using v3.0.0. Can you upgrade to v3.0.2 and let me know if you still get errors? It should be fixed in that version.

**Comment by andygarfield** [comment]
> Also, while I can't pin to Pydantic < 2 you can in your project. If you install pydantic < 2 as your own dependency `camel-converter` can use it.

Yeah, that would work

**Comment by sanders41** [comment]
I'm going to close this, but if you continue to have issues after updating camel-converter or pinning pydantic feel free to re-open it.
